### ISSUE TITLE
Incorrect pass status for incomplete on JS lesson 

### ISSUE THREAD

**Issue by nickaldwin** [codedex-io/javascript-101#60]
Hello, I noticed a bug in the JavaScript lesson. After creating a new account to start over, I found that when I click 'Complete' without following the lesson guide, I am still marked as having passed the exercises. I’ve included a screenshot for reference. I don’t have a solution for this; I just want to help. I love Codedex, and I think it's a great platform for learning the basics.

![Screenshot 2024-10-21 141402](https://github.com/user-attachments/assets/6bfe5f2f-43c7-4c0e-bac7-9ba0b5f51495)

**Comment by intelagense** [comment]
Thanks for the report and the kind words! ❤️ 

This is the intended behavior of the platform, though it might seem confusing at first. The idea is to let learners use their own code editor or setup if they want, instead of just using the built-in editor. Marking a task as complete is really just for tracking your own progress, like checking off items on a to-do list.

**Comment by intelagense** [comment]
Thanks for the report and the kind words! ❤️

This is the intended behavior of the platform, though it might seem confusing at first. The idea is to let learners use their own code editor or setup if they want, instead of just using the built-in editor. Marking a task as complete is really just for tracking your own progress, like checking off items on a to-do list.

**Comment by nickaldwin** [comment]
@intelagense it makes sense to me now. Thank you so much
